# Generated by Django 5.0.2 on 2024-07-29 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_livro_alter_autor_options_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="livro",
            name="categoria",
            field=models.ForeignKey(
                default=2, on_delete=django.db.models.deletion.PROTECT, related_name="livros", to="core.categoria"
            ),
            preserve_default=False,
        ),
    ]
