# Generated by Django 5.0.2 on 2024-08-12 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_livro_autor"),
    ]

    operations = [
        migrations.AddField(
            model_name="livro",
            name="coautor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="livros_coautor",
                to="core.autor",
            ),
        ),
        migrations.AlterField(
            model_name="livro",
            name="autor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="livros_autor",
                to="core.autor",
            ),
        ),
        migrations.AlterField(
            model_name="livro",
            name="preco",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name="Preço"
            ),
        ),
        migrations.AlterField(
            model_name="livro",
            name="titulo",
            field=models.CharField(max_length=255, verbose_name="Título"),
        ),
    ]
