# Generated by Django 5.0.2 on 2024-08-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_livro_coautor_alter_livro_autor_alter_livro_preco_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="livro",
            name="autor",
        ),
        migrations.RemoveField(
            model_name="livro",
            name="coautor",
        ),
        migrations.AddField(
            model_name="livro",
            name="autores",
            field=models.ManyToManyField(blank=True, related_name="livros", to="core.autor"),
        ),
    ]
